version: 0.2

phases:
  install:
    commands:
      - echo "Install"
  build:
  commands:
    - echo "Breaking build intentionally"
    - exit 1

artifacts:
  files:
    - "**/*"
  base-directory: dist
